Hooks:PostHook(MusicManager, "init", "dzedbaradzed_sortmusiclist_init", function(self)
    table.sort(tweak_data.music.track_list, function(a,b)
        return managers.localization:text("menu_jukebox_" .. a.track) < managers.localization:text("menu_jukebox_" .. b.track)
    end)
    table.sort(tweak_data.music.track_ghost_list, function(a,b)
        return managers.localization:text("menu_jukebox_screen_" .. a.track) < managers.localization:text("menu_jukebox_screen_" .. b.track)
    end)
    table.sort(tweak_data.music.track_menu_list, function(a,b)
        return managers.localization:text("menu_jukebox_screen_" .. a.track) < managers.localization:text("menu_jukebox_screen_" .. b.track)
    end)
end)
